
### Scan Dependencies

POST http://127.0.0.1:11001/vscn/scan
Content-Type: application/json

{
  "dependencies": [
    {
      "product": "antlr",
      "version": "2.7.7"
    },
    {
      "product": "logback-classic",
      "version": "1.2.3"
    },
    {
      "product": "logback-core",
      "version": "1.2.3"
    },
    {
      "product": "jackson-annotations",
      "version": "2.11.2"
    },
    {
      "product": "jackson-core",
      "version": "2.11.2"
    },
    {
      "product": "jackson-databind",
      "version": "2.11.2"
    },
    {
      "product": "jackson-datatype-jdk8",
      "version": "2.11.2"
    },
    {
      "product": "jackson-datatype-jsr310",
      "version": "2.11.2"
    },
    {
      "product": "jackson-module-parameter-names",
      "version": "2.11.2"
    },
    {
      "product": "classmate",
      "version": "1.5.1"
    },
    {
      "product": "json-path",
      "version": "2.4.0"
    },
    {
      "product": "jakarta.activation",
      "version": "1.2.2"
    },
    {
      "product": "istack-commons-runtime",
      "version": "3.0.11"
    },
    {
      "product": "android-json",
      "version": "0.0.20131108.vaadin1"
    },
    {
      "product": "HikariCP",
      "version": "3.4.5"
    },
    {
      "product": "commons-codec",
      "version": "1.14"
    },
    {
      "product": "netty-buffer",
      "version": "4.1.52.Final"
    },
    {
      "product": "netty-codec-http2",
      "version": "4.1.52.Final"
    },
    {
      "product": "netty-codec-http",
      "version": "4.1.52.Final"
    },
    {
      "product": "netty-codec-socks",
      "version": "4.1.52.Final"
    },
    {
      "product": "netty-codec",
      "version": "4.1.52.Final"
    },
    {
      "product": "netty-common",
      "version": "4.1.52.Final"
    },
    {
      "product": "netty-handler-proxy",
      "version": "4.1.52.Final"
    },
    {
      "product": "netty-handler",
      "version": "4.1.52.Final"
    },
    {
      "product": "netty-resolver",
      "version": "4.1.52.Final"
    },
    {
      "product": "netty-transport-native-epoll",
      "version": "4.1.52.Final"
    },
    {
      "product": "netty-transport-native-unix-common",
      "version": "4.1.52.Final"
    },
    {
      "product": "netty-transport",
      "version": "4.1.52.Final"
    },
    {
      "product": "reactor-netty",
      "version": "0.9.12.RELEASE"
    },
    {
      "product": "reactor-core",
      "version": "3.3.10.RELEASE"
    },
    {
      "product": "jakarta.activation-api",
      "version": "1.2.2"
    },
    {
      "product": "jakarta.annotation-api",
      "version": "1.3.5"
    },
    {
      "product": "jakarta.persistence-api",
      "version": "2.2.3"
    },
    {
      "product": "jakarta.transaction-api",
      "version": "1.3.3"
    },
    {
      "product": "jakarta.xml.bind-api",
      "version": "2.3.3"
    },
    {
      "product": "javax.activation-api",
      "version": "1.2.0"
    },
    {
      "product": "jaxb-api",
      "version": "2.3.1"
    },
    {
      "product": "junit",
      "version": "4.13"
    },
    {
      "product": "byte-buddy-agent",
      "version": "1.10.14"
    },
    {
      "product": "byte-buddy",
      "version": "1.10.14"
    },
    {
      "product": "accessors-smart",
      "version": "1.2"
    },
    {
      "product": "json-smart",
      "version": "2.3"
    },
    {
      "product": "httpclient",
      "version": "4.5.12"
    },
    {
      "product": "httpcore",
      "version": "4.4.13"
    },
    {
      "product": "log4j-api",
      "version": "2.13.3"
    },
    {
      "product": "log4j-to-slf4j",
      "version": "2.13.3"
    },
    {
      "product": "tomcat-embed-core",
      "version": "9.0.38"
    },
    {
      "product": "tomcat-embed-websocket",
      "version": "9.0.38"
    },
    {
      "product": "apiguardian-api",
      "version": "1.1.0"
    },
    {
      "product": "aspectjweaver",
      "version": "1.9.6"
    },
    {
      "product": "assertj-core",
      "version": "3.16.1"
    },
    {
      "product": "bcpkix-jdk15on",
      "version": "1.65"
    },
    {
      "product": "bcprov-jdk15on",
      "version": "1.65"
    },
    {
      "product": "checker-qual",
      "version": "3.5.0"
    },
    {
      "product": "dom4j",
      "version": "2.1.3"
    },
    {
      "product": "jaxb-runtime",
      "version": "2.3.3"
    },
    {
      "product": "txw2",
      "version": "2.3.3"
    },
    {
      "product": "jakarta.el",
      "version": "3.0.3"
    },
    {
      "product": "hamcrest",
      "version": "2.2"
    },
    {
      "product": "hibernate-commons-annotations",
      "version": "5.1.0.Final"
    },
    {
      "product": "hibernate-core",
      "version": "5.4.21.Final"
    },
    {
      "product": "javassist",
      "version": "3.24.0-GA"
    },
    {
      "product": "jboss-logging",
      "version": "3.4.1.Final"
    },
    {
      "product": "jandex",
      "version": "2.1.3.Final"
    },
    {
      "product": "junit-jupiter-api",
      "version": "5.6.2"
    },
    {
      "product": "junit-jupiter-engine",
      "version": "5.6.2"
    },
    {
      "product": "junit-jupiter-params",
      "version": "5.6.2"
    },
    {
      "product": "junit-jupiter",
      "version": "5.6.2"
    },
    {
      "product": "junit-platform-commons",
      "version": "1.6.2"
    },
    {
      "product": "junit-platform-engine",
      "version": "1.6.2"
    },
    {
      "product": "junit-vintage-engine",
      "version": "5.6.2"
    },
    {
      "product": "keycloak-adapter-core",
      "version": "11.0.2"
    },
    {
      "product": "keycloak-adapter-spi",
      "version": "11.0.2"
    },
    {
      "product": "keycloak-authz-client",
      "version": "11.0.2"
    },
    {
      "product": "keycloak-common",
      "version": "11.0.2"
    },
    {
      "product": "keycloak-core",
      "version": "11.0.2"
    },
    {
      "product": "keycloak-spring-boot-adapter-core",
      "version": "11.0.2"
    },
    {
      "product": "keycloak-spring-boot-starter",
      "version": "11.0.2"
    },
    {
      "product": "keycloak-spring-security-adapter",
      "version": "11.0.2"
    },
    {
      "product": "spring-boot-container-bundle",
      "version": "11.0.2"
    },
    {
      "product": "mockito-core",
      "version": "3.3.3"
    },
    {
      "product": "mockito-junit-jupiter",
      "version": "3.3.3"
    },
    {
      "product": "objenesis",
      "version": "2.6"
    },
    {
      "product": "opentest4j",
      "version": "1.2.0"
    },
    {
      "product": "asm",
      "version": "5.0.4"
    },
    {
      "product": "postgresql",
      "version": "42.2.16"
    },
    {
      "product": "lombok",
      "version": "1.18.12"
    },
    {
      "product": "reactive-streams",
      "version": "1.0.3"
    },
    {
      "product": "jsonassert",
      "version": "1.5.0"
    },
    {
      "product": "jul-to-slf4j",
      "version": "1.7.30"
    },
    {
      "product": "slf4j-api",
      "version": "1.7.30"
    },
    {
      "product": "spring-boot-autoconfigure",
      "version": "2.3.4.RELEASE"
    },
    {
      "product": "spring-boot-configuration-processor",
      "version": "2.3.4.RELEASE"
    },
    {
      "product": "spring-boot-starter-aop",
      "version": "2.3.4.RELEASE"
    },
    {
      "product": "spring-boot-starter-data-jpa",
      "version": "2.3.4.RELEASE"
    },
    {
      "product": "spring-boot-starter-jdbc",
      "version": "2.3.4.RELEASE"
    },
    {
      "product": "spring-boot-starter-json",
      "version": "2.3.4.RELEASE"
    },
    {
      "product": "spring-boot-starter-logging",
      "version": "2.3.4.RELEASE"
    },
    {
      "product": "spring-boot-starter-reactor-netty",
      "version": "2.3.4.RELEASE"
    },
    {
      "product": "spring-boot-starter-security",
      "version": "2.3.4.RELEASE"
    },
    {
      "product": "spring-boot-starter-test",
      "version": "2.3.4.RELEASE"
    },
    {
      "product": "spring-boot-starter-tomcat",
      "version": "2.3.4.RELEASE"
    },
    {
      "product": "spring-boot-starter-web",
      "version": "2.3.4.RELEASE"
    },
    {
      "product": "spring-boot-starter-webflux",
      "version": "2.3.4.RELEASE"
    },
    {
      "product": "spring-boot-starter",
      "version": "2.3.4.RELEASE"
    },
    {
      "product": "spring-boot-test-autoconfigure",
      "version": "2.3.4.RELEASE"
    },
    {
      "product": "spring-boot-test",
      "version": "2.3.4.RELEASE"
    },
    {
      "product": "spring-boot",
      "version": "2.3.4.RELEASE"
    },
    {
      "product": "spring-data-commons",
      "version": "2.3.4.RELEASE"
    },
    {
      "product": "spring-data-jpa",
      "version": "2.3.4.RELEASE"
    },
    {
      "product": "spring-security-config",
      "version": "5.3.4.RELEASE"
    },
    {
      "product": "spring-security-core",
      "version": "5.3.4.RELEASE"
    },
    {
      "product": "spring-security-web",
      "version": "5.3.4.RELEASE"
    },
    {
      "product": "spring-aop",
      "version": "5.2.9.RELEASE"
    },
    {
      "product": "spring-aspects",
      "version": "5.2.9.RELEASE"
    },
    {
      "product": "spring-beans",
      "version": "5.2.9.RELEASE"
    },
    {
      "product": "spring-context",
      "version": "5.2.9.RELEASE"
    },
    {
      "product": "spring-core",
      "version": "5.2.9.RELEASE"
    },
    {
      "product": "spring-expression",
      "version": "5.2.9.RELEASE"
    },
    {
      "product": "spring-jcl",
      "version": "5.2.9.RELEASE"
    },
    {
      "product": "spring-jdbc",
      "version": "5.2.9.RELEASE"
    },
    {
      "product": "spring-orm",
      "version": "5.2.9.RELEASE"
    },
    {
      "product": "spring-test",
      "version": "5.2.9.RELEASE"
    },
    {
      "product": "spring-tx",
      "version": "5.2.9.RELEASE"
    },
    {
      "product": "spring-web",
      "version": "5.2.9.RELEASE"
    },
    {
      "product": "spring-webflux",
      "version": "5.2.9.RELEASE"
    },
    {
      "product": "spring-webmvc",
      "version": "5.2.9.RELEASE"
    },
    {
      "product": "nio-multipart-parser",
      "version": "1.1.0"
    },
    {
      "product": "nio-stream-storage",
      "version": "1.1.3"
    },
    {
      "product": "xmlunit-core",
      "version": "2.7.0"
    },
    {
      "product": "snakeyaml",
      "version": "1.26"
    }
  ]
}

### Get Cve

GET http://localhost:11001/vscn/cve?id=CVE-2020-35490&id=CVE-2021-22096